<?php

/**
 * @file
 * Contains program_pendidikan.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function program_pendidikan_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the program_pendidikan module.
    case 'help.page.program_pendidikan':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Pengelolaan progra pendidikan') . '</p>';
      return $output;

    default:
  }
}
